### ISSUE TITLE
Improvements.

### ISSUE THREAD

**Issue by insidert** [lokeshboddula/college-website#1]
1. No need to wrap Navbar component inside a container-fluid when we need a full-width navbar. The container-fluid class leaves a small margin on the left and right. We still can wrap inside any grid-related class for alignment according to the need. If we need a full-width navbar without any margins, just leave it inside NAV tag after the opening body tag.

2. For the content other than the navbar use container and then row and then column classes. We can wrap all rows within one container or one row inside one container. Doing the latter will give more flexibility when styling.

3. We can do the same for individual headings too. Wrap inside a container, row and a column class.

**Comment by lokeshboddula** [comment]
I have made the changes sir!
